// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn0pULVBJXZoMaSFD3KAYVNnyZxFCkZ_U',
    appId: '1:1056053513868:web:a8d21d7468846923f175a9',
    messagingSenderId: '1056053513868',
    projectId: 'airjetkids-9d045',
    authDomain: 'airjetkids-9d045.firebaseapp.com',
    storageBucket: 'airjetkids-9d045.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN6UX0pEbJXXYn7S9jFUyy_qMwH3AGU7I',
    appId: '1:1056053513868:android:98ea69a57240f9d7f175a9',
    messagingSenderId: '1056053513868',
    projectId: 'airjetkids-9d045',
    storageBucket: 'airjetkids-9d045.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdD0c-Hzsm80TD4PqbcXDoEQydTaMQZJs',
    appId: '1:1056053513868:ios:46322c7757994cbef175a9',
    messagingSenderId: '1056053513868',
    projectId: 'airjetkids-9d045',
    storageBucket: 'airjetkids-9d045.firebasestorage.app',
    iosBundleId: 'com.example.arBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdD0c-Hzsm80TD4PqbcXDoEQydTaMQZJs',
    appId: '1:1056053513868:ios:46322c7757994cbef175a9',
    messagingSenderId: '1056053513868',
    projectId: 'airjetkids-9d045',
    storageBucket: 'airjetkids-9d045.firebasestorage.app',
    iosBundleId: 'com.example.arBeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn0pULVBJXZoMaSFD3KAYVNnyZxFCkZ_U',
    appId: '1:1056053513868:web:7a7bffa4a83ebc38f175a9',
    messagingSenderId: '1056053513868',
    projectId: 'airjetkids-9d045',
    authDomain: 'airjetkids-9d045.firebaseapp.com',
    storageBucket: 'airjetkids-9d045.firebasestorage.app',
  );
}
