name: ar_beta
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  latlong2: ^0.9.1
  get_storage: ^2.0.3
  get: ^4.6.5
  permission_handler: ^10.4.3
  vector_math: ^2.1.0
  logger: ^1.1.0
  arcore_flutter_plugin: ^0.1.0
  path_provider: ^2.0.15
  firebase_core: ^2.8.0
  firebase_database: ^10.1.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  shared_preferences: ^2.1.0
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true        # Android için ikon üret
  ios: true            # iOS için ikon üret
  image_path: "images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/
